#!/usr/bin/env node
// Copies the exact three.js files the page imports (plus their import graph) and the two
// web fonts into public/vendor so Bullpen works with no network access.
//   node scripts/vendor.mjs [path-to-extracted-three-package]
// Without an argument it downloads three@<THREE_VERSION> from the npm registry.
import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const THREE_VERSION = '0.170.0';
const ENTRIES = ['controls/OrbitControls.js', 'postprocessing/EffectComposer.js', 'postprocessing/RenderPass.js', 'postprocessing/GTAOPass.js', 'postprocessing/OutputPass.js'];
const FONT_CSS = 'https://fonts.googleapis.com/css2?family=Press+Start+2P&family=IBM+Plex+Mono:wght@400;600&display=swap';
const SUBSETS = new Set(['latin', 'latin-ext']);

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'public', 'vendor');

let pkg = process.argv[2];
if (!pkg) {
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'three-'));
  const tgz = path.join(tmp, 'three.tgz');
  console.log(`downloading three@${THREE_VERSION}`);
  const res = await fetch(`https://registry.npmjs.org/three/-/three-${THREE_VERSION}.tgz`);
  if (!res.ok) throw new Error(`three download failed: ${res.status}`);
  await fs.writeFile(tgz, Buffer.from(await res.arrayBuffer()));
  execFileSync('tar', ['xzf', tgz, '-C', tmp]);
  pkg = path.join(tmp, 'package');
}
const version = JSON.parse(await fs.readFile(path.join(pkg, 'package.json'), 'utf8')).version;
if (version !== THREE_VERSION) console.warn(`warning: vendoring three ${version}, page was written against ${THREE_VERSION}`);

// three: walk relative imports from the entry addons
await fs.rm(path.join(out, 'three'), { recursive: true, force: true });
const jsm = path.join(pkg, 'examples', 'jsm');
const seen = new Set();
async function walk(rel) {
  if (seen.has(rel)) return; seen.add(rel);
  const src = path.join(jsm, rel);
  const text = await fs.readFile(src, 'utf8');
  const dst = path.join(out, 'three', 'examples', 'jsm', rel);
  await fs.mkdir(path.dirname(dst), { recursive: true });
  await fs.writeFile(dst, text);
  for (const m of text.matchAll(/(?:import|export)\s[^'"]*?from\s*['"]([^'"]+)['"]|import\s*\(\s*['"]([^'"]+)['"]\s*\)/g)) {
    const spec = m[1] || m[2];
    if (!spec || !spec.startsWith('.')) continue; // 'three' resolves via the importmap
    await walk(path.posix.normalize(path.posix.join(path.posix.dirname(rel), spec)));
  }
}
for (const e of ENTRIES) await walk(e);
await fs.mkdir(path.join(out, 'three', 'build'), { recursive: true });
await fs.copyFile(path.join(pkg, 'build', 'three.module.js'), path.join(out, 'three', 'build', 'three.module.js'));
await fs.copyFile(path.join(pkg, 'LICENSE'), path.join(out, 'three', 'LICENSE'));
await fs.writeFile(path.join(out, 'three', 'VERSION'), `${version}\n`);
console.log(`three ${version}: three.module.js + ${seen.size} addon files`);

// fonts: latin subsets only, woff2, self-hosted
await fs.rm(path.join(out, 'fonts'), { recursive: true, force: true });
await fs.mkdir(path.join(out, 'fonts'), { recursive: true });
const css = await (await fetch(FONT_CSS, { headers: { 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36' } })).text();
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
let localCss = '/* Self-hosted copies of Google Fonts (OFL 1.1): Press Start 2P, IBM Plex Mono. Generated by scripts/vendor.mjs */\n';
let n = 0;
for (const [, subset, block] of blocks) {
  if (!SUBSETS.has(subset)) continue;
  const family = block.match(/font-family:\s*'([^']+)'/)[1].replace(/\s+/g, '');
  const weight = block.match(/font-weight:\s*(\d+)/)[1];
  const url = block.match(/url\((https:[^)]+)\)/)[1];
  const file = `${family}-${weight}-${subset}.woff2`;
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  await fs.writeFile(path.join(out, 'fonts', file), buf);
  localCss += `/* ${subset} */\n${block.replace(url, `./fonts/${file}`)}\n`;
  n++;
}
await fs.writeFile(path.join(out, 'fonts.css'), localCss);
console.log(`fonts: ${n} woff2 files`);
